### ISSUE TITLE
Bug: FoF extensions (and maybe others) don't get the translations

### ISSUE THREAD

**Issue by iPurpl3x** [flarum-lang/french#34]
I just recently installed this pack and tried to make it work for third party extensions. I have many extensions installed but to demonstrate my problem I only enabled FoF User Directory. 

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/18526076/122176559-0b455f00-ce85-11eb-99a9-1473ae775b43.png">

In this source code of this language pack, I can clearly see that this extension is translated, but when I check the coverage with Linguist (or check the UI), the `fof-user-directory` of this language pack don't work... It's very strange because everything seems to be fine in the language pack and in the configuration of my Flarum instance! I did this test with a fresh flarum instance with all defaults just installed and activated flarum-lang/french, fof/user-directory & fof/linguist.

I guess this problem affects many third party extensions.

(cc @Hiobi)

**Comment by Hiobi** [comment]
Hi @iPurpl3x,

Thanks for your issue. 
Currently this repository is being migrated and merged, conflicts may persist. With @qiaeru  we have been working on the release of a stable and up to date version. 
I'm investigating on this issue !

Thanks

**Comment by iPurpl3x** [comment]
Alright, looking forward for a working update! Let me know if I can help.

**Comment by Hiobi** [comment]
Yes ! You can help us with translations, directly on Weblate : https://weblate.rob006.net/languages/fr/flarum/
There is lot of work and a helping hand is always welcome. :+1: 

Thanks !

**Comment by Hiobi** [comment]
So! 
I made a clean install of flarum 1.0.2 with docker, I install FoF/Linguist and FoF/User-drectory.
I installed the dev-master of flarum-lang/french and everything works, translation appear. 

So I can suppose that you added the last stable release, not the dev-master.
You can install and install it with this command:

`composer require flarum-lang/french:dev-master`

**Comment by iPurpl3x** [comment]
Perfect. Yes with `dev-master` it works fine! Thanks.
