### ISSUE TITLE
"Se connecter pour répondre" trop long

### ISSUE THREAD

**Issue by krodelabestiole** [flarum-lang/french#35]
Bonjour, quand on lit une discussion sans être connecté, le texte du bouton d'action sur la droite déborde du bouton. Je pense que ce texte est de toute manière trop long pour convenir à un bouton, contrairement à _Log In to Reply_.
Le problème est particulièrement visible quand la couleur du texte est différente de celle du fond, mais il est de toute façon gênant.

On pourrait remplacer ce texte par simplement _Répondre_ par ex. ?

**Comment by Hiobi** [comment]
Hello @krodelabestiole,

C'est plutôt @qiaeru qui gère la traduction du Core, ceci dit je fais le même constat, je suppose que Qiaeru aussi. C'est là, toute la difficulté de la traduction : interpréter sans perdre le sens. 

Mettre uniquement "Répondre" fait perdre une partie de l'information, à savoir qu'il va falloir se connecter pour "répondre". 

Merci !

**Comment by krodelabestiole** [comment]
> Mettre uniquement "Répondre" fait perdre une partie de l'information, à savoir qu'il va falloir se connecter pour "répondre".

certes, mais _Se connecter pou_ fait encore moins de sens je crois ^^
il faut simplement accepter ce petit compromis, l'utilisateur découvrira de lui-même qu'il faut se connecter si il veut répondre, ça me semble pas très grave...

**Comment by qiaeru** [comment]
Bonjour @krodelabestiole ! Tu as tout as fait raison. J'avais soulevé à l'époque le problème aux développeurs pour qu'ils puissent mettre en place une taille dynamique du texte, qui serait rentré dans le bouton en diminuant la taille du texte. À l'époque, on m'avait répondu que cela allait être implémenté. Quelques années plus tard, ce n'est pas le cas, il faut donc s'adapter en conséquence. Ce sera donc corrigé lors de la sortie de la prochaine version stable de la traduction. 🙂

**Comment by qiaeru** [comment]
Corrigé : https://github.com/flarum-lang/french/commit/3d95504e4c8e94df3d6103f6b8f2d1b9509513dc
