### ISSUE TITLE
Incorrect translation for `Pin` 

### ISSUE THREAD

**Issue by ArtFlag** [flarum-lang/french#66]
Hi/Bonjour! 

When we pin a thread, the hover indicates `Epingler` but that's not a CTA so it should be `Epinglé`, in this case/context.

<img width="177" alt="Screenshot 2024-06-24 at 20 34 40" src="https://github.com/flarum-lang/french/assets/25686502/7cbe1154-2db7-473f-80e0-668538ba6766">

**Comment by qiaeru** [comment]
Thanks, I fixed this in the next version of the language pack. 👍

**Comment by ArtFlag** [comment]
Hi @qiaeru, thanks for the quick action.

I updated and now I see: 
![Screenshot 2024-07-06 at 19 01 25](https://github.com/flarum-lang/french/assets/25686502/1e6dfefc-f975-4960-a8ec-d8a827ab2481)


This is not correct, it should be `Épinglé`. Not `Épingler`, and not `Épingle`.

**Comment by qiaeru** [comment]
Yes, I checked the language keys and the original translation is "Pin", not "Pinned". So the author wants to indicate that the icon is a pin, not that the discussion is pinned.
