### ISSUE TITLE
Date Bug in Thread View

### ISSUE THREAD

**Issue by DB-CH** [flarum-lang/french#68]
see attached screenshot.

it should not say AMAMAM, it should be 2024 ;-) 

English and German are displayed correct.
![Bildschirmfoto_1-11-2024_182333_forum vsh-suisse ch](https://github.com/user-attachments/assets/5f6c05c8-5185-4b7c-bb02-51ce70e5bb0b)

**Comment by qiaeru** [comment]
Mmmh I can't reproduce the issue on my side.

**Comment by qiaeru** [comment]
Also reported here: https://discuss.flarum.org/d/615-french-language-pack/372

**Comment by qiaeru** [comment]
This should be resolved with the new release: https://github.com/flarum-lang/french/pull/69#pullrequestreview-2440911258
